FROM python:3.12-slim AS builder

WORKDIR /app

COPY pyproject.toml poetry.lock* /app/

COPY deploy/configs/config_user_microservice.toml /app/deploy/configs/

RUN pip install poetry

RUN poetry config virtualenvs.create false && poetry install --no-interaction --no-ansi --no-root

COPY user_microservice /app/user_microservice


CMD ["uvicorn", "user_microservice.main.web:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
